#!/bin/bash
ip link set dev eth1 up 
ip link set dev eth0 up 
ip addr add 120.7.250.129/26 dev eth1
ip addr add 120.7.250.193/26 dev eth0

service quagga start
#ip route add default via 120.7.250.130

#On drop tout
iptables -P INPUT DROP
iptables -P OUTPUT DROP
iptables -P FORWARD DROP

iptables -A INPUT -p udp --dport 520 -j ACCEPT
iptables -A OUTPUT -p udp --dport 520 -j ACCEPT
iptables -A FORWARD -p udp --dport 520 -j ACCEPT

#ON autorise les pings (icmp)
iptables -t filter -A OUTPUT -p icmp -j ACCEPT
iptables -t filter -A INPUT -p icmp -j ACCEPT
iptables -t filter -A FORWARD -p icmp -j ACCEPT



#Autorisation DNS
iptables -t filter -A FORWARD -d 120.7.250.194 -s 120.7.250.1 -p udp --dport 53 -j ACCEPT #Accepte tout depuis la boxe 1 vers le dns
iptables -t filter -A FORWARD -d 120.7.250.194 -s 120.7.250.33 -p udp --dport 53 -j ACCEPT #Accepte tout depuis la boxe 2 vers le dns
iptables -t filter -A FORWARD -s 120.7.250.194 -p udp --sport 53 -j ACCEPT #Accepte tout depuis le DNS


#Autorisation HTTPS
iptables -A FORWARD -d 120.7.250.195 -s 120.7.250.33 -p tcp --dport 80 -j ACCEPT
iptables -A FORWARD -d 120.7.250.195 -s 120.7.250.1 -p tcp --dport 80 -j ACCEPT
iptables -A FORWARD -s 120.7.250.195 -p tcp --sport 80 -j ACCEPT

#Affichage de la table iptables
#iptables -L

