#!/bin/bash
ip link set dev eth0 up
ip link set dev eth1 up

ip addr add 192.168.163.1/25 dev eth0
ip addr add 170.3.1.193/26 dev eth1

echo 1 > /proc/sys/net/ipv4/ip_forward

ip route add default via 170.3.1.195


#Mises en place du DHCP pour l'attribution des adresses
service isc-dhcp-server start 

#Mises en place du SNAT
iptables -t nat -A POSTROUTING -s 192.168.63.0/25 -o eth1 -j SNAT --to-source 170.3.1.193
#Tout ce qui vient du réseau 192.168.63.0/25 depuis, on le change et on dit que la source est 170.3.1.193

#On drop tout, on verra ensuite ce que l'on doit accepter
iptables -P INPUT DROP
iptables -P OUTPUT DROP
iptables -P FORWARD DROP

#ON autorise les pings (icmp)
iptables -t filter -A OUTPUT -p icmp -j ACCEPT
iptables -t filter -A INPUT -p icmp -j ACCEPT
iptables -t filter -A FORWARD -p icmp -j ACCEPT

#Autorisation DHCP
iptables -A INPUT -i eth1 -p udp --dport 67:68 --sport 67:68 -j ACCEPT 



