#!/bin/bash
ip link set dev eth0 up
ip link set dev eth1 up

ip addr add  170.3.1.1/26 dev eth0
ip addr add  170.3.1.67/26 dev eth1

echo 1 > /proc/sys/net/ipv4/ip_forward

#On drop tout
iptables -P INPUT DROP
iptables -P OUTPUT DROP
iptables -P FORWARD DROP

iptables -A INPUT -p udp --dport 520 -j ACCEPT
iptables -A OUTPUT -p udp --dport 520 -j ACCEPT
iptables -A FORWARD -p udp --dport 520 -j ACCEPT

#ON autorise les pings (icmp)
iptables -t filter -A OUTPUT -p icmp -j ACCEPT
iptables -t filter -A INPUT -p icmp -j ACCEPT
iptables -t filter -A FORWARD -p icmp -j ACCEPT


#Autorisation DNS
iptables -t filter -A FORWARD -d 170.3.1.2 -s 170.3.1.193 -p udp --dport 53 -j ACCEPT #Accepte tout depuis la boxe 1 vers le dns
iptables -t filter -A FORWARD -d 170.3.1.2 -s 170.3.1.194 -p udp --dport 53 -j ACCEPT #Accepte tout depuis la boxe 2 vers le dns
iptables -t filter -A FORWARD -s 170.3.1.2 -p udp --sport 53 -j ACCEPT #Accepte tout depuis le DNS

#Autorisation HTTPS
iptables -A FORWARD -d 170.3.1.3 -s 170.3.1.193 -p tcp --dport 80 -j ACCEPT
iptables -A FORWARD -d 170.3.1.3 -s 170.3.1.194 -p tcp --dport 80 -j ACCEPT
iptables -A FORWARD -s 170.3.1.3 -p tcp --sport 80 -j ACCEPT

service quagga start
