#!/bin/bash
ip link set dev eth0 up 
ip link set dev eth1 up

ip addr add 192.168.63.1/25 dev eth0
ip addr add 170.3.1.194/26 dev eth1

echo 1 > /proc/sys/net/ipv4/ip_forward

ip route add default via 170.3.1.195

#Mises en place du DHCP pour l'attribution des adresses
service isc-dhcp-server start 

#mises en place du snat
iptables -t nat -A POSTROUTING -s 192.168.63.0/25 -o eth0 -j SNAT --to-source 170.3.1.194

#Mises en place du DNAT 
iptables -t nat -A PREROUTING -p tcp -d 170.3.1.194 -j DNAT --to 192.168.85.3
#Tout ce qui va a 170.3.1.194 depuis le port 80 on l'accepte et one le redirige vers 192.168.85.3

#On drop tout
iptables -P INPUT DROP
iptables -P OUTPUT DROP
iptables -P FORWARD DROP

#ON autorise les pings (icmp)
iptables -t filter -A OUTPUT -p icmp -j ACCEPT
iptables -t filter -A INPUT -p icmp -j ACCEPT
iptables -t filter -A FORWARD -p icmp -j ACCEPT

#Autorisation DHCP
iptables -A INPUT -i eth0 -p udp --dport 67:68 --sport 67:68 -j ACCEPT

#Autorisation DNS
iptables -t filter -A FORWARD -d 170.3.1.2/26 -p udp --dport 53 -j ACCEPT
iptables -t filter -A FORWARD -s 170.3.1.2/26 -p udp --sport 53 -j ACCEPT

#Autorisation HTTPS vers DMZ
iptables -A FORWARD -d 170.3.1.3/26 -p tcp --dport 80 -j ACCEPT
iptables -A FORWARD -s 170.3.1.3/26 -p tcp --sport 80 -j ACCEPT

#Affichage de la table iptables
#iptables -L








